SELECT * FROM CLIENTE;
SELECT * FROM EMPLEADO;


SELECT 
    FECHA_NAC_CLI   
FROM CLIENTE
WHERE TO_CHAR(FECHA_NAC_CLI, 'MONTH') LIKE TO_CHAR(SYSDATE, 'MONTH') AND EXTRACT(DAY FROM FECHA_NAC_CLI) LIKE EXTRACT(DAY FROM SYSDATE+1);

SELECT
    NUMRUN_EMP || '-' || DVRUN_EMP AS "RUN EMPLEADO",
    PNOMBRE_EMP ||' '|| SNOMBRE_EMP ||' '|| APPATERNO_EMP ||' '|| APMATERNO_EMP AS "NOMBRE COMPLETO EMPLEADO",
    SUELDO_BASE AS "SUELDO BASE",
    TRUNC(SUELDO_BASE/100000) AS "PORCENTAJE DE MOVILIZACIÓN",
    ROUND(TRUNC(SUELDO_BASE/100000)/100 * SUELDO_BASE,0) AS "VALOR MOVILIZACIÓN"
FROM EMPLEADO;

SELECT
    NUMRUN_EMP || '-' || DVRUN_EMP AS "RUN EMPLEADO",
    PNOMBRE_EMP ||' '|| SNOMBRE_EMP ||' '|| APPATERNO_EMP ||' '|| APMATERNO_EMP AS "NOMBRE COMPLETO EMPLEADO",
    SUELDO_BASE AS "SUELDO BASE",
    TO_CHAR(FECHA_NAC, 'DD/MM/YYYY') AS "FECHA NACIMIENTO",
    SUBSTR(PNOMBRE_EMP,1,3)||LENGTH(PNOMBRE_EMP)||'*'||SUBSTR(TO_CHAR(SUELDO_BASE),LENGTH(SUELDO_BASE))||DVRUN_EMP||TRUNC((MONTHS_BETWEEN(SYSDATE, FECHA_CONTRATO))/12) AS "NOMBRE DE USUARIO",
    SUBSTR(NUMRUN_EMP, 3,0)
FROM EMPLEADO;
