SELECT * FROM ALUMNO;
SELECT * FROM CARRERA;
SELECT * FROM EMPLEADO;

SELECT
    CARRERAID AS "IDENTIFICADOR DE LA CARRERA",
    COUNT(CARRERAID) AS "TOTAL ALUMNOS MATRICULADOS",
    'Le corresponden'||TO_CHAR(COUNT(CARRERAID)*30200, '$999G999')||' '|| 'del presupuesto total asignado para publicidad ' AS "MONTO POR PUBLICIDAD"
FROM ALUMNO
GROUP BY CARRERAID
ORDER BY COUNT(CARRERAID) DESC;

SELECT
    CARRERAID AS "CARRERA",
    COUNT(CARRERAID) AS "TOTAL DE ALUMNOS"
FROM ALUMNO
HAVING COUNT(CARRERAID) > 4
GROUP BY CARRERAID;

SELECT
    TO_CHAR(RUN_JEFE, '99G999G999') AS "RUN JEFE SIN DV",
    COUNT(RUN_JEFE) AS "TOTAL EMPLEADOS A SU CARGO",
    MAX(SALARIO) AS "SALARIO MAXIMO",
    COUNT(RUN_JEFE) * 10 ||'% DEL SALARIO MAXIMO' AS "PORCENTAJE DE BONIFICACION",
    TO_CHAR(MAX(SALARIO)*(COUNT(RUN_JEFE)/10), '$99G999G999') AS "BONIFICACION"
FROM EMPLEADO
WHERE RUN_JEFE IS NOT NULL
GROUP BY RUN_JEFE;


SELECT
    ID_ESCOLARIDAD AS "ESCOLARIDAD",
    (CASE WHEN ID_ESCOLARIDAD = 10 THEN 'BASICA'
    WHEN ID_ESCOLARIDAD = 20 THEN 'MEDIA CIENTIFICA HUMANISTA'
    WHEN ID_ESCOLARIDAD = 30 THEN 'MEDIA TECNICO PROFESIONAL'
    WHEN ID_ESCOLARIDAD = 40 THEN 'SUPERIOR CENTRO DE FORMACIÓN TÉCNICA'
    WHEN ID_ESCOLARIDAD = 50 THEN 'SUPERIOR INSTITUTO PROFESIONAL'
    WHEN ID_ESCOLARIDAD = 60 THEN 'SUPERIOR UNIVERSIDAD' END) AS "DESCRIPCION ESCOLARIDAD",
    COUNT(ID_ESCOLARIDAD) AS "TOTAL EMPLEADOS",
    TO_CHAR(MAX(SALARIO), '$99G999G999') AS "SALARIO MAXIMO",
    TO_CHAR(MIN(SALARIO), '$99G999G999') AS "SALARIO MINIMO",
    TO_CHAR(SUM(SALARIO), '$99G999G999')  AS "SALARIO TOTAL",
    TO_CHAR(AVG(SALARIO), '$99G999G999')  AS "SALARIO PROMEDIO"
FROM EMPLEADO
GROUP BY ID_ESCOLARIDAD;


SELECT
    TITULOID AS "CODIGO DEL LIBRO",
    COUNT(PRESTAMOID) AS "TOTAL DE VECES SOLICITADO",
    (CASE WHEN COUNT(PRESTAMOID) = 1 THEN 'NO SE REQUIEREN EJEMPLARES'
    WHEN COUNT(PRESTAMOID) BETWEEN 2 AND 3 THEN 'SE REQUIERE COMPRAR 1 NUEVOS EJEMPLARES'
    WHEN COUNT(PRESTAMOID) BETWEEN 4 AND 5 THEN 'SE REQUIERE COMPRAR 2 NUEVOS EJEMPLARES'
    WHEN COUNT(PRESTAMOID) > 5 THEN 'SE REQUIEREN COMPRAR 4 NUEVOS EJEMPLARES' END)
FROM PRESTAMO
WHERE EXTRACT(YEAR FROM FECHA_DEVOLUCION) = 2021
GROUP BY TITULOID
ORDER BY COUNT(PRESTAMOID) DESC;

SELECT
    TO_CHAR(RUN_EMP,'99G999G999') AS "RUN EMPLEADO",
    TO_CHAR(FECHA_INI_PRESTAMO, 'MM/YYYY') AS "MES PRESTAMO LIBROS",
    COUNT(RUN_EMP) AS "TOTAL PRESTAMOS ATENDIDOS",
    TO_CHAR(count(run_emp)*10000,'$99G999G999') as "ASIGNACION POR PRESTAMOS" 
FROM PRESTAMO
WHERE EXTRACT(YEAR FROM FECHA_INI_PRESTAMO) = 2020
GROUP BY RUN_EMP,TO_CHAR(FECHA_INI_PRESTAMO, 'MM/YYYY')
order by "MES PRESTAMO LIBROS";
