SELECT * FROM PROPIEDAD;
SELECT * FROM PROPIEDAD_ARRENDADA;
SELECT * FROM CLIENTE;
SELECT * FROM ESTADO_CIVIL;
SELECT * FROM EMPLEADO;
-- CASO 1
SELECT
    FECHA_ENTREGA_PROPIEDAD
FROM PROPIEDAD;

SELECT
    FECINI_ARRIENDO AS "FECHA INICIO ARRIENDO"
FROM PROPIEDAD_ARRENDADA;

SELECT
    FECHA_ENTREGA_PROPIEDAD
FROM PROPIEDAD
WHERE TO_CHAR(FECHA_ENTREGA_PROPIEDAD, 'DD/MM/YYYY') LIKE '%%/%%/2022';

SELECT
    FECINI_ARRIENDO AS "FECHA INICIO ARRIENDO"
FROM PROPIEDAD_ARRENDADA
WHERE TO_CHAR(FECINI_ARRIENDO, 'DD/MM/YYYY') LIKE '%%/%%/2022'

--CASO 2

SELECT
    NUMRUT_CLI ||'-'||DVRUT_CLI AS "RUT CLIENTE",
    NOMBRE_CLI ||' '|| APPATERNO_CLI ||' '|| APMATERNO_CLI AS "NOMBRE CLIENTE",
    RENTA_CLI AS "RENTA",
    FONOFIJO_CLI AS "TELEFONO FIJO",
    CELULAR_CLI AS "CELULAR"
FROM CLIENTE
WHERE ID_ESTCIVIL IN(1, 3, 4) AND RENTA_CLI > 800000
ORDER BY APPATERNO_CLI;

--CASO 3

SELECT
     NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP AS "NOMBRE EMPLEADO",
     SUELDO_EMP AS "SUELDO ACTUAL",
     SUELDO_EMP * 1.085 AS "SUELDO REAJUSTADO",
     SUELDO_EMP * 0.085 AS "AUMENTO"
FROM EMPLEADO
ORDER BY SUELDO_EMP * 0.085 DESC;

SELECT
     NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP AS "NOMBRE EMPLEADO",
     SUELDO_EMP AS "SUELDO ACTUAL",
     SUELDO_EMP * 1.20 AS "SUELDO REAJUSTADO",
     SUELDO_EMP * 0.20 AS "AUMENTO"
FROM EMPLEADO
WHERE SUELDO_EMP BETWEEN 200000 AND 400000
ORDER BY SUELDO_EMP * 0.20 DESC;

SELECT
    NUMRUT_EMP ||'-'|| DVRUT_EMP AS "RUN EMPLEADO",
    NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP AS "NOMBRE EMPLEADO",
    SUELDO_EMP AS "SALARIO ACTUAL",
    SUELDO_EMP * &BONIFICACION/100 AS "BONIFICACION EXTRA"
FROM EMPLEADO
WHERE SUELDO_EMP < 500000
ORDER BY APPATERNO_EMP;

SELECT
    NRO_PROPIEDAD AS "NUMERO PROPIEDAD",
    TO_CHAR(FECHA_ENTREGA_PROPIEDAD) AS "FECHA ENTREGA PROPIEDAD",
    DIRECCION_PROPIEDAD AS "DIRECCION PROPIEDAD",
    SUPERFICIE,
    NRO_DORMITORIOS AS "CANTIDAD DE DORMITORIOS",
    NRO_BANOS AS "CANTIDAD DE BAÑOS",
    VALOR_ARRIENDO AS "VALOR ARRIENDO"
FROM PROPIEDAD
WHERE TO_CHAR(FECHA_ENTREGA_PROPIEDAD, 'DD/MM/YYYY') LIKE '%%/%%/2022'
ORDER BY FECHA_ENTREGA_PROPIEDAD ASC;

SELECT
    NRO_PROPIEDAD AS "NUMERO PROPIEDAD",
    TO_CHAR(FECHA_ENTREGA_PROPIEDAD) AS "FECHA ENTREGA PROPIEDAD",
    DIRECCION_PROPIEDAD AS "DIRECCION PROPIEDAD",
    SUPERFICIE,
    NRO_DORMITORIOS AS "CANTIDAD DE DORMITORIOS",
    NRO_BANOS AS "CANTIDAD DE BAÑOS",
    VALOR_ARRIENDO AS "VALOR ARRIENDO"
FROM PROPIEDAD
WHERE TO_CHAR(FECHA_ENTREGA_PROPIEDAD, 'DD/MM/YYYY') LIKE '%%/02/2010'
ORDER BY FECHA_ENTREGA_PROPIEDAD ASC;
