SELECT * FROM CLIENTE;
SELECT * FROM PROFESION_OFICIO;
SELECT * FROM CREDITO_CLIENTE;
SELECT * FROM CREDITO;
SELECT * FROM TIPO_CLIENTE;

SELECT
    TO_CHAR(CLI.NUMRUN, '99G999G999') ||'-'|| CLI.DVRUN AS "RUN CLIENTE",
    CLI.PNOMBRE ||' '|| CLI.SNOMBRE ||' '|| CLI.APPATERNO ||' '|| CLI.APMATERNO AS "NOMBRE CLIENTE",
    PRO.NOMBRE_PROF_OFIC AS "PROFESION/OFICIO",
    TO_CHAR(FECHA_NACIMIENTO, 'DD "de" MONTH') AS "DIA DE CUMPLEAÑOS"
FROM CLIENTE CLI JOIN PROFESION_OFICIO PRO ON (CLI.COD_PROF_OFIC = PRO.COD_PROF_OFIC)
WHERE EXTRACT(MONTH FROM FECHA_NACIMIENTO) =  EXTRACT(MONTH FROM SYSDATE) + 1;


SELECT
    TO_CHAR(CLI.NUMRUN, '99G999G999') ||'-'|| CLI.DVRUN AS "RUN CLIENTE",
    CLI.PNOMBRE ||' '|| CLI.SNOMBRE ||' '|| CLI.APPATERNO ||' '|| CLI.APMATERNO AS "NOMBRE CLIENTE",
    TO_CHAR(CRE.MONTO_SOLICITADO, '$99G999G999') AS "MONTO SOLICITADO CREDITOS",
    TO_CHAR(CRE.MONTO_SOLICITADO * 0.012, '$99G999G999') AS "TOTAL PESOS TODOSUMA"
FROM CLIENTE CLI JOIN CREDITO_CLIENTE CRE ON (CLI.NRO_CLIENTE = CRE.NRO_CLIENTE)
WHERE EXTRACT(YEAR FROM FECHA_OTORGA_CRED) = EXTRACT(YEAR FROM SYSDATE) -1
ORDER BY "TOTAL PESOS TODOSUMA";

SELECT
    TO_CHAR(CC.FECHA_OTORGA_CRED, 'MM/YYYY') AS "MES TRANSACCION",
    CRE.NOMBRE_CREDITO AS "TIPO CREDITO",
    TO_CHAR(CC.MONTO_SOLICITADO, '$99G999G999') AS "MONTO SOLICITADO CREDITO",
    (CASE WHEN CC.MONTO_SOLICITADO BETWEEN 100000 AND 1000000 THEN TO_CHAR(CC.MONTO_SOLICITADO * 0.01, '$99G999G999')
    WHEN CC.MONTO_SOLICITADO BETWEEN 1000001 AND 2000000 THEN TO_CHAR(CC.MONTO_SOLICITADO * 0.02, '$99G999G999')
    WHEN CC.MONTO_SOLICITADO BETWEEN 2000001 AND 4000000 THEN TO_CHAR(CC.MONTO_SOLICITADO * 0.03, '$99G999G999')
    WHEN CC.MONTO_SOLICITADO BETWEEN 4000001 AND 6000000 THEN TO_CHAR(CC.MONTO_SOLICITADO * 0.04, '$99G999G999')
    WHEN CC.MONTO_SOLICITADO > 6000000 THEN TO_CHAR(CC.MONTO_SOLICITADO * 0.07, '$99G999G999') END) AS "APORTE A LA SBIF"
FROM CREDITO CRE JOIN CREDITO_CLIENTE CC ON (CRE.COD_CREDITO = CC.COD_CREDITO)
WHERE EXTRACT(YEAR FROM CC.FECHA_OTORGA_CRED) = EXTRACT(YEAR FROM SYSDATE)-1
ORDER BY "MES TRANSACCION", CRE.NOMBRE_CREDITO;

SELECT
    TO_CHAR(CLI.NUMRUN, '99G999G999')||'-'|| CLI.DVRUN AS "RUN CLIENTE",
    CLI.PNOMBRE ||' '|| CLI.SNOMBRE ||' '|| CLI.APPATERNO ||' '|| CLI.APMATERNO AS "NOMBRE CLIENTE",
    TO_CHAR(SUM(PIC.MONTO_TOTAL_AHORRADO), '$99G999G999') AS "MONTO TOTAL AHORRADO",
    (CASE WHEN SUM(PIC.MONTO_TOTAL_AHORRADO) BETWEEN 100000 AND 1000000 THEN 'BRONCE'
    WHEN SUM(PIC.MONTO_TOTAL_AHORRADO) BETWEEN 1000001 AND 4000000 THEN 'PLATA'
    WHEN SUM(PIC.MONTO_TOTAL_AHORRADO) BETWEEN 4000001 AND 8000000 THEN 'SILVER'
    WHEN SUM(PIC.MONTO_TOTAL_AHORRADO) BETWEEN 8000001 AND 15000000 THEN 'GOLD'
    WHEN SUM(PIC.MONTO_TOTAL_AHORRADO) > 15000000 THEN 'PLATINUM' END) AS "CATEGORIA CLIENTE"
FROM CLIENTE CLI JOIN PRODUCTO_INVERSION_CLIENTE PIC ON (CLI.NRO_CLIENTE = PIC.NRO_CLIENTE)
GROUP BY CLI.NUMRUN, CLI.DVRUN, CLI.PNOMBRE, CLI.SNOMBRE, CLI.APPATERNO, CLI.APMATERNO
ORDER BY CLI.APPATERNO;

SELECT
    EXTRACT(YEAR FROM SYSDATE) AS "AÑO TIRBUTARIO",
    TO_CHAR(CLI.NUMRUN, '99G999G999') ||'-'|| CLI.DVRUN AS "RUN CLIENTE",
    CLI.PNOMBRE ||' '|| CLI.SNOMBRE ||' '|| CLI.APPATERNO ||' '|| CLI.APMATERNO AS "NOMBRE CLIENTE",
    COUNT(PIC.COD_PROD_INV) AS "TOTAL PROD. INV AFECTOS IMPTO",
    TO_CHAR(SUM(PIC.MONTO_TOTAL_AHORRADO), '$99G999G999') AS "MONTO TOTAL AHORRADO"
FROM CLIENTE CLI JOIN PRODUCTO_INVERSION_CLIENTE PIC ON (CLI.NRO_CLIENTE = PIC.NRO_CLIENTE)
WHERE PIC.COD_PROD_INV >= 30
GROUP BY CLI.NUMRUN, CLI.DVRUN, CLI.PNOMBRE, CLI.SNOMBRE, CLI.APPATERNO, CLI.APMATERNO
ORDER BY CLI.APPATERNO;

