SELECT
    TO_CHAR(CLI.NUMRUN, '99G999G999') ||'-'|| CLI.DVRUN AS "RUN CLIENTE",
    CLI.PNOMBRE ||' '|| CLI.SNOMBRE||'  '|| CLI.APPATERNO||' '|| CLI.APMATERNO AS "NOMBRE CLIENTE",
    TO_CHAR(CLI.FECHA_NACIMIENTO, 'DD "de" MONTH') AS "DIA DE CUMPLEAÑOS",
    SR.DIRECCION AS "SUCURSAL"
FROM CLIENTE CLI JOIN COMUNA CO ON (CLI.COD_COMUNA = CO.COD_COMUNA AND CLI.COD_PROVINCIA = CO.COD_PROVINCIA AND CLI.COD_REGION = CO.COD_REGION)
    JOIN SUCURSAL_RETAIL SR ON (SR.COD_COMUNA = CO.COD_COMUNA AND SR.COD_PROVINCIA = CO.COD_PROVINCIA AND SR.COD_REGION = CO.COD_REGION)
WHERE EXTRACT(MONTH FROM CLI.FECHA_NACIMIENTO) = EXTRACT(MONTH FROM SYSDATE)-1
ORDER BY "DIA DE CUMPLEAÑOS" , CLI.APPATERNO;

SELECT
    TO_CHAR(CLI.NUMRUN, '99G999G999') ||'-'|| CLI.DVRUN AS "RUN CLIENTE",
    CLI.PNOMBRE ||' '|| CLI.SNOMBRE||' '|| CLI.APPATERNO||' '|| CLI.APMATERNO AS "NOMBRE CLIENTE",
    TO_CHAR(SUM(TTC.MONTO_TRANSACCION), '$99G999G999') AS "MONTO COMPRAS/AVANCES/S.AVANCES",
    TO_CHAR(ROUND((SUM(TTC.MONTO_TRANSACCION)/10000)*250), '999G999') AS "TOTAL PUNTOS ACUMULADOS"
FROM CLIENTE CLI JOIN TARJETA_CLIENTE TC ON (CLI.NUMRUN = TC.NUMRUN)
    JOIN TRANSACCION_TARJETA_CLIENTE TTC ON (TC.NRO_TARJETA = TTC.NRO_TARJETA)
WHERE EXTRACT(YEAR FROM FECHA_TRANSACCION) = EXTRACT(YEAR FROM SYSDATE)-1
GROUP BY CLI.NUMRUN, CLI.DVRUN, CLI.PNOMBRE, CLI.SNOMBRE, CLI.APPATERNO, CLI.APMATERNO
ORDER BY "TOTAL PUNTOS ACUMULADOS", CLI.APPATERNO;

SELECT
    TO_CHAR(TTC.FECHA_TRANSACCION, 'MMYYYY') AS "MES TRANSACCION",
    TTT.NOMBRE_TPTRAN_TARJETA AS "TIPO TRANSACCION",
    TO_CHAR(SUM(TTC.MONTO_TOTAL_TRANSACCION), '$99G999G999') AS "MONTO AVANCES/SUPER AVANCES",
    (CASE WHEN SUM(TTC.MONTO_TOTAL_TRANSACCION) < 100000 THEN TO_CHAR(ROUND(SUM(TTC.MONTO_TOTAL_TRANSACCION)*0), '$999G999') 
    WHEN SUM(TTC.MONTO_TOTAL_TRANSACCION) BETWEEN 100000 AND 1000000 THEN TO_CHAR(ROUND(SUM(TTC.MONTO_TOTAL_TRANSACCION)*0.01), '$999G999')
    WHEN SUM(TTC.MONTO_TOTAL_TRANSACCION) BETWEEN 1000001 AND 2000000 THEN TO_CHAR(ROUND(SUM(TTC.MONTO_TOTAL_TRANSACCION)*0.02), '$999G999')
    WHEN SUM(TTC.MONTO_TOTAL_TRANSACCION) BETWEEN 2000001 AND 4000000 THEN TO_CHAR(ROUND(SUM(TTC.MONTO_TOTAL_TRANSACCION)*0.03), '$999G999')
    WHEN SUM(TTC.MONTO_TOTAL_TRANSACCION) BETWEEN 4000001 AND 6000000 THEN TO_CHAR(ROUND(SUM(TTC.MONTO_TOTAL_TRANSACCION)*0.04), '$999G999')
    WHEN SUM(TTC.MONTO_TOTAL_TRANSACCION) BETWEEN 6000001 AND 9999999999 THEN TO_CHAR(ROUND(SUM(TTC.MONTO_TOTAL_TRANSACCION)*0.07), '$999G999') END) AS "APORTE SBIF"
FROM TRANSACCION_TARJETA_CLIENTE TTC JOIN TIPO_TRANSACCION_TARJETA TTT ON (TTC.COD_TPTRAN_TARJETA = TTT.COD_TPTRAN_TARJETA)
WHERE TTT.COD_TPTRAN_TARJETA IN(103, 102)
GROUP BY TO_CHAR(TTC.FECHA_TRANSACCION, 'MMYYYY'), TTT.NOMBRE_TPTRAN_TARJETA
ORDER BY "MES TRANSACCION", "TIPO TRANSACCION";

SELECT 
    TO_CHAR(cli.NUMRUN,'99G999G999')||'-'||
    cli.DVRUN AS "RUN CLIENTE",
    cli.PNOMBRE || ' ' || cli.SNOMBRE || ' ' || cli.APPATERNO || ' ' || cli.APMATERNO AS "NOMBRE CLIENTE",
    NVL(TO_CHAR(SUM(ttc.MONTO_TOTAL_TRANSACCION), '$999G999G999'), TO_CHAR(0,'$9')) AS "MONTO AVANCES/SUPER AVANCES",
    NVL((CASE WHEN SUM(ttc.MONTO_TOTAL_TRANSACCION) BETWEEN 0 and  999999 THEN 'SIN CATEGORIZAR'
    WHEN SUM(ttc.MONTO_TOTAL_TRANSACCION) BETWEEN 100000 and 1000000 THEN 'BRONCE'
    WHEN SUM(ttc.MONTO_TOTAL_TRANSACCION) BETWEEN 1000001 and 4000000 THEN 'PLATA'
    WHEN SUM(ttc.MONTO_TOTAL_TRANSACCION) BETWEEN 4000001 and 8000000 THEN 'SILVER'
    WHEN SUM(ttc.MONTO_TOTAL_TRANSACCION) BETWEEN 8000001 and 15000000 THEN 'GOLD'
    WHEN SUM(ttc.MONTO_TOTAL_TRANSACCION) > 15000000 THEN 'PATINUM' END), 'SIN CATEGORIZAR') AS "CATEGORIA CLIENTE"
FROM CLIENTE cli FULL OUTER JOIN TARJETA_CLIENTE tc ON (cli.numrun = tc.numrun)
    FULL OUTER JOIN TRANSACCION_TARJETA_CLIENTE ttc ON (tc.NRO_TARJETA = ttc.NRO_TARJETA)
GROUP BY cli.NUMRUN, cli.DVRUN, cli.PNOMBRE, cli.SNOMBRE, cli.APPATERNO, cli.APMATERNO;
