SELECT * FROM CLIENTE;
SELECT * FROM PROFESION_OFICIO;
SELECT * FROM CREDITO_CLIENTE;
SELECT * FROM CREDITO;
SELECT * FROM TIPO_CLIENTE;

SELECT
    TO_CHAR(CLI.NUMRUN, '99G999G999') ||'-'|| CLI.DVRUN AS "RUN CLIENTE",
    CLI.PNOMBRE ||' '|| CLI.SNOMBRE ||' '|| CLI.APPATERNO ||' '|| CLI.APMATERNO AS "NOMBRE CLIENTE",
    PRO.NOMBRE_PROF_OFIC AS "PROFESION/OFICIO",
    TO_CHAR(FECHA_NACIMIENTO, 'DD "de" MONTH') AS "DIA DE CUMPLEAÑOS"
FROM CLIENTE CLI JOIN PROFESION_OFICIO PRO ON (CLI.COD_PROF_OFIC = PRO.COD_PROF_OFIC)
WHERE EXTRACT(MONTH FROM FECHA_NACIMIENTO) =  EXTRACT(MONTH FROM SYSDATE) + 1;


SELECT
    TO_CHAR(CLI.NUMRUN, '99G999G999') ||'-'|| CLI.DVRUN AS "RUN CLIENTE",
    CLI.PNOMBRE ||' '|| CLI.SNOMBRE ||' '|| CLI.APPATERNO ||' '|| CLI.APMATERNO AS "NOMBRE CLIENTE",
    TO_CHAR(CRE.MONTO_SOLICITADO, '$99G999G999') AS "MONTO SOLICITADO CREDITOS",
    TO_CHAR(CRE.MONTO_SOLICITADO * 0.012, '$99G999G999') AS "TOTAL PESOS TODOSUMA"
FROM CLIENTE CLI JOIN CREDITO_CLIENTE CRE ON (CLI.NRO_CLIENTE = CRE.NRO_CLIENTE)
WHERE EXTRACT(YEAR FROM FECHA_OTORGA_CRED) = EXTRACT(YEAR FROM SYSDATE) -1
ORDER BY "TOTAL PESOS TODOSUMA";
