SELECT
    TO_CHAR(CLI.NUMRUN, '99G999G999') ||'-'|| CLI.DVRUN AS "RUN CLIENTE",
    CLI.PNOMBRE ||' '|| CLI.SNOMBRE||'  '|| CLI.APPATERNO||' '|| CLI.APMATERNO AS "NOMBRE CLIENTE",
    TO_CHAR(CLI.FECHA_NACIMIENTO, 'DD "de" MONTH') AS "DIA DE CUMPLEAÑOS",
    SR.DIRECCION AS "SUCURSAL"
FROM CLIENTE CLI JOIN COMUNA CO ON (CLI.COD_COMUNA = CO.COD_COMUNA AND CLI.COD_PROVINCIA = CO.COD_PROVINCIA AND CLI.COD_REGION = CO.COD_REGION)
    JOIN SUCURSAL_RETAIL SR ON (SR.COD_COMUNA = CO.COD_COMUNA AND SR.COD_PROVINCIA = CO.COD_PROVINCIA AND SR.COD_REGION = CO.COD_REGION)
WHERE EXTRACT(MONTH FROM CLI.FECHA_NACIMIENTO) = EXTRACT(MONTH FROM SYSDATE)-1
ORDER BY "DIA DE CUMPLEAÑOS" , CLI.APPATERNO;
