SELECT * FROM JOBS;
SELECT * FROM EMPLOYEES;
SELECT
    *
FROM JOBS
WHERE MIN_SALARY > 10000;

SELECT
    FIRST_NAME,
    HIRE_DATE 
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '01/01/02' AND '31/12/05';

SELECT
    FIRST_NAME AS "NOMBRE",
    HIRE_DATE AS "FECHA DE CONTRATACIÓN"
FROM EMPLOYEES
WHERE JOB_ID IN('IT_PROG', 'SA_MAN');

SELECT *
FROM EMPLOYEES
WHERE HIRE_DATE > '01/01/2008';

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN(150,160);

SELECT
    FIRST_NAME,
    SALARY,
    COMMISSION_PCT,
    HIRE_DATE
FROM EMPLOYEES
WHERE SALARY < 10000;

SELECT
    JOB_TITLE,
    MAX_SALARY - MIN_SALARY
FROM JOBS
WHERE MAX_SALARY - MIN_SALARY BETWEEN 10000 AND 20000 ;

SELECT
    FIRST_NAME,
    SALARY,
    ROUND(SALARY, -2) AS "SALARY_ROUNDED"
FROM EMPLOYEES;

SELECT *
FROM JOBS
ORDER BY JOB_TITLE;

SELECT
    FIRST_NAME,
    LAST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'S%' OR LAST_NAME LIKE 'S%';

SELECT *
FROM EMPLOYEES
WHERE HIRE_DATE LIKE '%%/05/%%';

SELECT *
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL AND SALARY BETWEEN 5000 AND 10000 AND DEPARTMENT_ID = 50;

SELECT *
FROM EMPLOYEES;

SELECT *
FROM JOBS;

SELECT 
    FIRST_NAME,
    HIRE_DATE,
    TRUNC(ADD_MONTHS(HIRE_DATE,1), 'MONTH') AS "PAYDAY"
FROM EMPLOYEES;

SELECT
    FIRST_NAME,
    HIRE_DATE,
    TRUNC(((to_date(SYSDATE, 'DD/MM/YYYY hh24:mi')- to_date(HIRE_DATE, 'DD/MM/YYYY hh24:mi'))/365)) AS "AÑOS DE EXPERIENCIA"
FROM EMPLOYEES;

SELECT
    FIRST_NAME,
    HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE LIKE '%%/%%/02';

SELECT
    JOB_TITLE,
    REGEXP_SUBSTR(JOB_TITLE, '(\S*)') AS "PRIMERA PALABRA"
FROM JOBS;

SELECT
    FIRST_NAME,
    LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE '__b%';

SELECT
    UPPER(FIRST_NAME),
    LOWER(EMAIL)
FROM EMPLOYEES;
    
SELECT *
FROM EMPLOYEES
WHERE HIRE_DATE LIKE '%%/%%/05';